#!/usr/bin/env bash
set -eu
source $(dirname ${BASH_SOURCE[0]})/koolbox-build-functions.inc

: ${KOOLBOX_BUILD_IMAGE_NAME:=kubebox}
: ${KOOLBOX_BUILD_IMAGE_SUBTAG=trixie}
: ${KOOLBOX_BUILD_FROM_IMAGE_NAME:=basebox}
: ${KOOLBOX_BUILD_FROM_IMAGE_TAG:=${KOOLBOX_VERSION}-${KOOLBOX_BUILD_IMAGE_SUBTAG}}

#KOOLBOX_INSTALL_APT_PACKAGES="curl ca-certificates git wget unzip zip less"
#KOOLBOX_INSTALL_DNF_PACKAGES="curl ca-certificates git wget unzip zip less"
#source $script_dir/inc/kubebox-apt.inc
#source $script_dir/inc/interactive-apt.inc

KOOLBOX_INSTALL_SCRIPTS="kubectl"



koolbox_build_main "${@}"
