#!/usr/bin/env bash
set -eu
source $(dirname ${BASH_SOURCE[0]})/koolbox-build-functions.inc

koolbox_build_init "$@"

KOOLBOX_BUILD_IMAGE_NAME=kubebox
KOOLBOX_BUILD_FROM_IMAGE_NAME=basebox


# old superslim KOOLBOX_INSTALL_APT_PACKAGES="curl ca-certificates "
# old slim      KOOLBOX_INSTALL_APT_PACKAGES+="git jq netcat-openbsd net-tools openssh-client wget unzip zip python3"
#export KOOLBOX_INSTALL_APT_PACKAGES="curl ca-certificates git wget unzip zip less"
#export KOOLBOX_INSTALL_DNF_PACKAGES="ca-certificates git-core wget unzip zip less"

KOOLBOX_INSTALL_SCRIPTS="kubectl"

if ${KOOLBOX_BUILD_FULL}; then
    KOOLBOX_INSTALL_SCRIPTS+=" kubectl-bash-completion"
fi

koolbox_build_image "${@}"
