#!/usr/bin/env bash
set -eu
source $(dirname ${BASH_SOURCE[0]})/koolbox-build-functions.inc

koolbox_build_init "$@"

KOOLBOX_BUILD_IMAGE_NAME=helmbox
KOOLBOX_BUILD_FROM_IMAGE_NAME=kubebox

KOOLBOX_INSTALL_SCRIPTS="helm"

koolbox_build_image "${@}"
