#!/usr/bin/env bash
set -eu
source $(dirname ${BASH_SOURCE[0]})/koolbox-build-functions.inc

koolbox_build_init "$@"

KOOLBOX_BUILD_IMAGE_NAME=kaazbox
KOOLBOX_BUILD_FROM_IMAGE_NAME=kubebox


# TODO: decide between apt, dnf, pip or script install?
KOOLBOX_INSTALL_SCRIPTS="azure-cli-script"
#KOOLBOX_INSTALL_APT_PACKAGES="apt-transport-https ca-certificates curl gnupg lsb-release"
#export KOOLBOX_INSTALL_APT_PACKAGES="pip"
#export KOOLBOX_INSTALL_SCRIPTS="apt-packages azure-cli-pip"

koolbox_build_image "${@}"
