#!/usr/bin/env bash
set -eu
source $(dirname ${BASH_SOURCE[0]})/koolbox-build-functions.inc


: ${KOOLBOX_BUILD_IMAGE_NAME:=basebox}
: ${KOOLBOX_BUILD_IMAGE_SUBTAG=trixie}
: ${KOOLBOX_BUILD_FROM:=debian:trixie}

KOOLBOX_INSTALL_APT_PACKAGES="curl ca-certificates git wget unzip zip less"
KOOLBOX_INSTALL_DNF_PACKAGES="curl ca-certificates git wget unzip zip less"

KOOLBOX_INSTALL_SCRIPTS="os-packages"

koolbox_build_main "${@}"
