#!/bin/bash
#set -e

export KOOLBOX_BASE_DIR=$(dirname $(dirname $(readlink -f ${BASH_SOURCE[0]})))

image_base=$(basename $0)

koolbox_main() {
    #koolbox_parse_options "$@"
    koolbox_load_config
    koolbox_run "${@}"
}

#koolbox_parse_options() {
    while [ ! $# -eq 0 ]; do
        case $1 in
            -h|--help)
                koolbox_help
                exit 0
                ;;
            -i|--image)
                KOOLBOX_RUN_IMAGE=$2;
                image_base=$2
                shift
                ;;
            --command|--)
                shift
                break
                ;;
            *)  # Default case: No more options, so break out of the loop.
                echo $1
                break
        esac
        shift
    done
#}


koolbox_help() {
    cat << EOF
Usage: ${0##*/} [options]

The purpose of koolboz is to run an image with some correct mounts
Options can be:
    -h|--help        display this help and exit
    -i|--image       the image to run (default kubebox)
EOF
}

koolbox_load_config() {
    KOOLBOX_DEFAULT_CONFIG_PATH=./$image_base.config
    KOOLBOX_DEFAULT_CONFIG_PATH+=:~/.config/koolbox
    KOOLBOX_DEFAULT_CONFIG_PATH+=:$KOOLBOX_BASE_DIR/config
    : ${KOOLBOX_CONFIG_PATH:=$KOOLBOX_DEFAULT_CONFIG_PATH}
    for path in ${KOOLBOX_CONFIG_PATH//:/ }; do
        #echo trying $path
        if [[ -f $path ]]; then
            echo reading config $path
            source $path
            break
        elif [[ -f $path/$image_base.config ]]; then
            echo reading config $path/$image_base.config
            source $path/$image_base.config
            break
        fi
    done
}

koolbox_run() {
    KOOLBOX_RUN_OPTIONS+=" --env HOME"
    KOOLBOX_RUN_OPTIONS+=" --workdir $(pwd)"
    # disable se_linux
    KOOLBOX_RUN_OPTIONS+=" --security-opt label=disable"
    KOOLBOX_RUN_OPTIONS+=" --userns keep-id"
    KOOLBOX_RUN_MOUNTS=$HOME
    for path in $KOOLBOX_RUN_MOUNTS; do
        KOOLBOX_RUN_OPTIONS+=" -v $path:$path"
    done
    podman run -it --rm  $KOOLBOX_RUN_OPTIONS $KOOLBOX_RUN_IMAGE "${@}"
}

koolbox_main "${@}"
